<!DOCTYPE html>
<html lang="es">
  
  <head>
    <meta charset="UTF-8" />
    <title>cuestionarios</title> 
  </head>
  
  <body>
  	<a href="index.php?controlador=cuestionarios&accion=crearcuestionario">+agregar cuestionario</a>
  	<table border="1">
  		<thead>
  			<th>id</th>
  			<th>nombre</th>
  			<th>email</th>
  			<th>password</th>
  			<th>opciones</th>
  		</thead>
  		<tbody>
  	

  <?php

   foreach ($datos as $dato) {
  
  echo "<tr>";

   echo "<td>" . $dato["id"] . "</td>";
   echo "<td>" . $dato["Componente"] . "</td>";
   echo "<td>" . $dato["correo"] . "</td>";
   echo "<td>" . $dato["contrasena"] . "</td>";
   echo "<td> 
      [<a href='index.php?controlador=cuestionarios&accion=actualizarcuestionario&id=".$dato['id']."'> Actualizar </a>] 
     [<a href='index.php?controlador=cuestionarios&accion=borrarcuestionario&id=".$dato['id']."'> Borrar </a>] 
      [<a href='index.php?controlador=cuestionarios&accion=vercuestionario&id=".$dato['id']."'> Ver </a>] </td>";


   echo "</tr>";
  
    }
  ?>
  </tbody>
  </table>
  </body>
</html>