<!DOCTYPE html>
<html lang="es">
  
  <head>
    <meta charset="UTF-8" />
    <title>Usuarios</title> 
  </head>
  
  <body>
  <form class="" action="index.php?controlador=usuarios&accion=guardaractualizacionusuario" method="post">
  	<p>
  	nombre: <input type="text" name="nombre" value="<?php echo $datos['nombre'] ?>">
    </p>
    <p>
  	email: <input type="text" name="correo" value="<?php echo $datos['correo'] ?>">
    </p>
    <p>
  	password: <input type="text" name="contrasena" value="<?php echo $datos['contrasena'] ?>">
    </p>

  	</select>
    
    <p>
    	<input type="hidden" name="id" value="<?php echo $datos['id']; ?>">
    	<input type="submit" name="" value="Guardar Usuario">
    </p>

    
  </form>
  </body>
</html>