<!DOCTYPE html>
<html lang="es">
  
  <head>
    <meta charset="UTF-8" />
    <title>Usuarios</title> 
  </head>
  
  <body>
  <form class="" action="index.php?controlador=usuarios&accion=guardarnuevousuario" method="post">
  	<p>
  	nombre: <input type="text" name="nombre" value="">
    </p>
    <p>
  	email: <input type="text" name="correo" value="">
    </p>
    <p>
  	password: <input type="text" name="contrasena" value="">
    </p>
   
  	</select>
    
    <p>
    	<input type="submit" name="" value="Guardar Usuario">
    </p>

    
  </form>
  </body>
</html>